pgvector-gist-1m-m16-200:
  dataset: gist-960-euclidean
  datasetType: hdf5
  pg_parallel_workers: 32
  metric: l2
  m: 16
  efConstruction: 200
  top: 10
  benchmarks:
    "80":  { efSearch: 80 }
    "160": { efSearch: 160 }
    "240": { efSearch: 240 }
    "350": { efSearch: 350 }
    "500": { efSearch: 500 }
    "700": { efSearch: 700 }
