pgvector-glove-1m-m16-128:
  dataset: glove-100-angular
  datasetType: hdf5
  pg_parallel_workers: 32
  metric: cos
  m: 16
  efConstruction: 128
  top: 10
  benchmarks:
    "40":  { efSearch: 40 }
    "80":  { efSearch: 80 }
    "140": { efSearch: 140 }
    "220": { efSearch: 220 }
    "350": { efSearch: 350 }
    "550": { efSearch: 550 }
