ariadne-sift-32-2k-b1:
  dataset: sift-128-euclidean
  datasetType: hdf5
  metric: l2
  k_outer: 32
  k_leaves: 2048
  samplingFactor: 256
  residual_quantization: true
  bits_per_dim: 1
  colocate_fp: fp16
  kmeans_iters: 15
  rerank_k: 100
  pg_parallel_workers: 32
  top: 10
  benchmarks:
    "3-10":   { probes: "3,10"   }
    "8-25":   { probes: "8,25"   }
    "13-40":  { probes: "13,40"  }
    "15-48":  { probes: "15,48"  }
    "20-64":  { probes: "20,64"  }
    "30-100": { probes: "30,100" }
