vc-sift-1m-32-2k:
  dataset: sift-128-euclidean
  datasetType: hdf5
  metric: l2
  samplingFactor: 256
  lists: [32, 2048]
  build_threads: 32
  residual_quantization: true
  kmeans_hierarchical: true
  pg_parallel_workers: 32
  top: 10
  benchmarks:
    3-10-1.9:
      nprob: 3,10
      epsilon: 1.9
    8-25-1.9:
      nprob: 8,25
      epsilon: 1.9
    13-40-1.9:
      nprob: 13,40
      epsilon: 1.9
    15-48-1.9:
      nprob: 15,48
      epsilon: 1.9
    20-64-1.9:
      nprob: 20,64
      epsilon: 1.9
    30-100-1.9:
      nprob: 30,100
      epsilon: 1.9
