ariadne-laion-5m-50-8k-seqlayout:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  metric: dot
  k_outer: 50
  k_leaves: 8000
  samplingFactor: 256
  residual_quantization: true
  kmeans_iters: 15
  bits_per_dim: 1
  colocate_fp: fp16
  rerank_k: 400
  pg_parallel_workers: 32
  top: 10
  query_bitquant: true
  benchmarks:
    "5-16":   { probes: "5,16"  }
    "8-25":   { probes: "8,25"  }
    "13-44":  { probes: "13,44" }
    "16-55":  { probes: "16,55" }
    "22-75":  { probes: "22,75" }
    "30-100": { probes: "30,100" }
