ariadne-deep1b-400-160k-b1-seqlayout:
  dataset: deep1b-test-l2
  datasetType: npy
  metric: l2
  k_outer: 400
  k_leaves: 160000
  sampling_factor: 256
  residual_quant: true
  kmeans_iters: 15
  bits_per_dim: 1
  colocate_fp: fp16
  pg_parallel_workers: 31
  rerank_k: 200
  top: 10
  benchmarks:
    "5-15":    { probes: "5,15"    }
    "10-25":   { probes: "10,25"   }
    "15-40":   { probes: "15,40"   }
    "20-50":   { probes: "20,50"   }
    "30-75":   { probes: "30,75"   }
    "40-100":  { probes: "40,100"  }
    "50-125":  { probes: "50,125"  }
    "60-150":  { probes: "60,150"  }
    "70-175":  { probes: "70,175"  }
    "80-200":  { probes: "80,200"  }
